# Generated by Django 4.2.8 on 2023-12-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_alter_destination_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
